POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "sandisahdewo",
    "password": "password"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "dicky",
}

###
// Divider for test message behaviour
###
GET http://localhost:3000/messages/1/14
Content-Type: application/json

###
GET http://localhost:3000/messages/group/1
Content-Type: application/json

###
// Divider for test groups behaviour
###
GET http://localhost:3000/groups
Content-Type: application/json

###
POST http://localhost:3000/groups
Content-Type: application/json

{
    "name": "A new group",
    "description": "Testing store new group"
}

###
PUT http://localhost:3000/groups/1
Content-Type: application/json

{
    "name": "A group updated name",
    "description": "Testing group updated description"
}

###
DELETE http://localhost:3000/groups/1
Content-Type: application/json

###
// Divider for test group participants behaviour
###
GET http://localhost:3000/group/1/participant
Content-Type: application/json

###
POST http://localhost:3000/group/2/participant
Content-Type: application/json

{
    "user_id": 2,
    "role": "member"
}