POST http://localhost:3000/auth/login
content-type: application/xml

{
    "username": "sandisahdewo",
    "password": "password"
}

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "dicky",
}